### ISSUE TITLE
Missing many module names in Italian language [Translation]

### ISSUE THREAD

**Issue by Dubita** [Eden-Project-Team/Eden-Update-Beta#2]
**Details**
- Game Version: 1.04
- Mod Version: 4.3.1 beta

**Describe the bug**
Many EP modules are named "BLANK" in Italian language 
![Screenshot_20230820_133917_Discord](https://github.com/Eden-Project-Team/Eden-Update-Beta/assets/59101824/31ef6501-602d-43ad-8180-697b4c729967)

**Comment by Stewie10** [comment]
That's normal cuz no translations for them yet. Only Japanese and English have everything right now

**Comment by testsnake** [comment]
How about we set everything that doesn't have a translation to either romaji or English?
