### ISSUE TITLE
!SECRET MODEL SPOILERS! New model only head showing up

### ISSUE THREAD

**Issue by MeerkatQueen** [Eden-Project-Team/Eden-Update-Beta#3]
- Game Version: 1.04
- 4.3.1 003

So I don't know if this is a conflict with another mod (will post list of potential conflicts), or the model itself is just unfinished and only serves as a simple teaser since it cannot be headswaped but for the "secret" new model only the head (and head accessory) shows up. Interestingly, after minimizing the program and opening it again, the model's icon which wasn't there before suddenly appeared. The icon doesn't show up at all in the song selection screen however.

The mods I have installed in this build are:
"! MegaMixThumbnailManager", "X Song Pack", "EdenProject", "Remove Unused spr_db entries", "#Kasane Teto Supremacy Pack1.1", "Alternate Skintone Modules", "Synchronizing Skin Color", "Eleanor Forte", "Beta Miku [Concept Miku]", "Kagamine ACT1 Modules", "Love Coloured Ward Module", "Kamui Gakupo", "Miku Append - Zero Ver", "Moyai Restoration", "Nightcord at 25-00 Module Pack", "Space Channel 5 Orange Suit", "Template Mod", "MORE MORE JUMP! Module Pack", "Mega extra singers", "ExPatch", "#Gothic Teto", "songlimitpatch", "Project Hoshikuzu - Module Pack", "Project Hoshikuzu - Song Pack", "D1ReccomendedModules", "Touch Grass", "Restore Cut Songs", "Skeelie Chart Pack #1 - Vocaloid", "Sekai Halloween Module Pack", "Ch6rlez's Sekai Pack", "Sekai Anniversary Module Pack", "MikuPa Modules", "XHD Module Pack", "FUCK", "Digital Stars 2021", and the one I did to add custom song variants but that doesn't have anything that conflicts and only has OGG files.

Note: Screenshots (except for the last one) will spoil the secret model. If you want it to stay a surprise please stop here. There won't be any further info from this point.

![gumibugmaybe](https://github.com/Eden-Project-Team/Eden-Update-Beta/assets/62972927/85ca616f-a39c-4e49-a6d8-d044d42bd711)
![gumibugmaybe2](https://github.com/Eden-Project-Team/Eden-Update-Beta/assets/62972927/9bb356b5-52cd-41f0-9d7e-2e5bc49be686)
![gumibugmaybe3](https://github.com/Eden-Project-Team/Eden-Update-Beta/assets/62972927/d4cf4f57-e949-43f1-8fa3-e56917f62e1e)

**Comment by C0rrupt3dSp1r1t** [comment]
I would like to add to this that it is not a module conflict, as I was trying to find out what it could be by gradually turning all mods not related to Eden off to see before making a report (which I'm late to be the one to post now,) though the issue persisted.

**Comment by Stewie10** [comment]
This happened to testsnake at one point too. I forgot how she fixed it, so just ask her

**Comment by testsnake** [comment]
I never managed to fix this issue, so I assume this has something to do with old files messing with it.

**Comment by Stewie10** [comment]
Ok here's the issue. U forgot to remove all the dlc4 files

**Comment by MeerkatQueen** [comment]
Went and deleted all the dlc4 files. She works now!
