### ISSUE TITLE
[BUG] Camera glitches on Lost One's Weeping

### ISSUE THREAD

**Issue by Static39** [Eden-Project-Team/Eden-Update-Beta#5]
**Details**
- Game Version: 1.04
- Mod Version: 4.3.1 Beta 005

**Describe the bug**
The camera seems to be broken on Lost One's Weeping.
When I play the song the camera stays fixed in place and is zoomed out.
I've tried disabling other mods and it doesn't seem to be a conflict issue.

![image](https://github.com/Eden-Project-Team/Eden-Update-Beta/assets/36354827/7b31bce4-29d6-4e5c-bb82-9c70e2271838)

**Other Mods Installed**
- ExPatch
- LyricsPatch

**Additional context**
The first time I attempted to play the song the game crashed, but every other time it has just been fixed camera.
I've also tried with multiple modules and have gotten the same result.

**Comment by Stewie10** [comment]
This works fine for me. Only thing i can think of is if u didnt delete all the dlc4 files

**Comment by Static39** [comment]
I've double checked that all the dlc4 files are gone and the issue persists. I'm fairly certain this song worked prior to the beta update, so I'm trying with a fresh install of 4.3 to see if the issue remains.
I've also got the crash report from the first time when it crashed if that is of any use.

**Comment by Static39** [comment]
I've tried with a fresh install of 4.3 and without the beta patch it runs fine, but when I use it the camera is messed up consistently.

**Comment by Stewie10** [comment]
I still don't see wut the issue could be cuz it works for me. Not sure about testsnake tho

**Comment by Static39** [comment]
Evidently, when I cloned the beta repository several files got corrupted.
Everything seems to working as expected now.
